sudo: required
services:
  - docker

before_install:
  - docker build -t dockerapp -f Dockerfile.dev .

scripts:
  - docker run -e CI=true dockerapp npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-app"
  env: "DockerReactApp-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-410956674706"
  bucket_path: "docker-react-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
